pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'BlockCorn'
include ':core'
include ':desktop'
// Android: independent Gradle project in android/
// iOS:     Xcode project in ios/
